# This is a basic workflow to help you get started with Actions
#VERSION 2

name: Image Migration
on:
  workflow_dispatch:
    inputs:
      source_registry:
        description: 'source image registry'
        required: true
        default: 'registry.k8s.io'
      source_app:
        description: 'source app image name'
        required: true
      source_app_tag:
        description: 'source app image tag'
        required: true
      target_registry:
        description: 'target registry'
        required: true
        default: 'lostar01'

jobs:
  migration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Pull Source Image
      run: |
        docker pull ${{ inputs.source_registry }}/${{ inputs.source_app }}/${{ inputs.source_app }}:${{ inputs.source_app_tag }}
      
    - name: Push Docker Hub
      run: |
        docker login -u ${{ secrets.HUBDOCKER_USER}} -p ${{ secrets.HUBDOCKER_PASSWD}} docker.io
        echo 'push image to target registry'
        docker tag ${{ inputs.source_registry }}/${{ inputs.source_app }}/${{ inputs.source_app }}:${{ inputs.source_app_tag }} ${{ inputs.target_registry }}/${{ inputs.source_app }}:${{ inputs.source_app_tag }}
        docker push ${{ inputs.target_registry }}/${{ inputs.source_app }}:${{ inputs.source_app_tag }}
