# This is a basic workflow to help you get started with Actions
#VERSION 2

name: Image Migration
on:
  workflow_dispath:
    source_image:
      description: 'source image which from global'
      required: true
    target_image:
      description: 'target image which will be push target registry'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Pull Source Image
      run |
        docker pull ${{github.event.inputs.source_image}}
      
    - name: Push Docker Hub
      run: |
        docker login -u ${{ secrets.HUBDOCKER_USER}} -p ${{ secrets.HUBDOCKER_PASSWD}} docker.io
        echo 'push image to target registry'
        docker tag ${{github.event.inputs.source_image}} ${{github.event.inputs.target_image}}
        docker push ${{github.event.inputs.target_image}}
